import { createHash } from "node:crypto";
import { mkdtemp, readFile, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { spawnSync } from "node:child_process";
import { describe, expect, it } from "vitest";

const BOOK_IDS = [
  "Gen", "Exod", "Lev", "Num", "Deut", "Josh", "Judg", "Ruth", "1Sam", "2Sam", "1Kgs", "2Kgs", "1Chr", "2Chr", "Ezra", "Neh", "Esth", "Job", "Ps", "Prov", "Eccl", "Song", "Isa", "Jer", "Lam", "Ezek", "Dan", "Hos", "Joel", "Amos", "Obad", "Jonah", "Mic", "Nah", "Hab", "Zeph", "Hag", "Zech", "Mal", "Matt", "Mark", "Luke", "John", "Acts", "Rom", "1Cor", "2Cor", "Gal", "Eph", "Phil", "Col", "1Thess", "2Thess", "1Tim", "2Tim", "Titus", "Phlm", "Heb", "Jas", "1Pet", "2Pet", "1John", "2John", "3John", "Jude", "Rev",
];

const generator = join(process.cwd(), "scripts/generatePublicBibleData.mjs");

function sha256(bytes) {
  return createHash("sha256").update(bytes).digest("hex");
}

function runGenerator(args) {
  return spawnSync(process.execPath, [generator, ...args], { encoding: "utf8" });
}

async function fixture() {
  const root = await mkdtemp(join(tmpdir(), "ohb-public-data-"));
  const biblePath = join(root, "bible.json");
  const resourcesPath = join(root, "resources.json");
  const outputPath = join(root, "public-data");
  const verses = BOOK_IDS.map((book) => ({ id: `${book}.1.1`, book, chapter: 1, verse: 1, text: `${book} text` }));
  await writeFile(biblePath, JSON.stringify({
    cuvBible: { id: "cuv", label: "和合本", language: "zh", verses },
    kjvBible: { id: "kjv", label: "KJV", language: "en", verses },
  }));
  await writeFile(resourcesPath, JSON.stringify({
    metadata: { sourceApiBase: "http://127.0.0.1:5127", reviewStatus: "needs_review" },
    resources: [
      {
        id: "gen-text", type: "commentary", title: "Genesis", body: "Safe body", verses: ["Gen.1.1"], primaryAnchor: "Gen.1.1", source: "Safe source",
        debugMeta: { sourceLabel: "Safe source", page: 3, sourcePdfPath: "/Users/simon/private.pdf", reviewStatus: "needs_review", sourceEvidenceSnippet: "private" },
      },
      { id: "gen-image", type: "image", title: "Private image", body: "", verses: ["Gen.1.1"], assetPath: "/resources/private.png" },
    ],
  }));
  return { biblePath, resourcesPath, outputPath };
}

describe("public Bible data generator", () => {
  it("writes exactly 66 safe text-only book packages with exact hashes", async () => {
    const { biblePath, resourcesPath, outputPath } = await fixture();
    const result = runGenerator(["--bible", biblePath, "--resources", resourcesPath, "--output", outputPath, "--release-version", "0.1.0"]);
    expect(result.stderr).toBe("");
    expect(result.status).toBe(0);

    const manifest = JSON.parse(await readFile(join(outputPath, "manifest.json"), "utf8"));
    const genesisBytes = await readFile(join(outputPath, "books/Gen.json"));
    const genesis = JSON.parse(genesisBytes);
    expect(manifest.books).toHaveLength(66);
    expect(manifest.books.map((book) => book.id)).toEqual(BOOK_IDS);
    expect(genesis.textCards.every((card) => card.type !== "image")).toBe(true);
    expect(JSON.stringify(genesis)).not.toMatch(/\/Users\/|127\.0\.0\.1|localhost/);
    expect(manifest.books.find((book) => book.id === "Gen").textCardCount).toBe(1);
    expect(sha256(genesisBytes)).toBe(manifest.books.find((book) => book.id === "Gen").sha256);
  });

  it("is deterministic, removes stale output, and validates generated bytes", async () => {
    const { biblePath, resourcesPath, outputPath } = await fixture();
    const args = ["--bible", biblePath, "--resources", resourcesPath, "--output", outputPath, "--release-version", "0.1.0"];
    expect(runGenerator(args).status).toBe(0);
    const firstManifest = await readFile(join(outputPath, "manifest.json"));
    await writeFile(join(outputPath, "stale.json"), "stale");
    expect(runGenerator(args).status).toBe(0);
    expect(await readFile(join(outputPath, "manifest.json"))).toEqual(firstManifest);
    expect(runGenerator(["--validate-only", outputPath]).status).toBe(0);
  });
});
