import type { VerseId } from "./verse";

export type ResourceType = "commentary" | "image" | "video" | "html" | "note" | "link";

export interface StudyResourceDebugMeta {
  fileName?: string;
  originalFileName?: string;
  replacementFileName?: string;
  sourceFolder?: string;
  sourcePackage?: string;
  sourcePdf?: string;
  sourcePdfPath?: string;
  sourcePdfSha256?: string;
  sourceManifestPath?: string;
  sourceLedgerPath?: string;
  sourceTextSource?: string;
  sourceTextSnippet?: string;
  sourceEvidenceType?: string;
  sourceEvidenceSnippet?: string;
  sourceEvidencePage?: number;
  sourceEvidenceOrigin?: string;
  sourceImageAlt?: string;
  sourceImageUrl?: string;
  sourceIndex?: number;
  sourceNavigationLinks?: Array<{ href: string; label: string }>;
  sourceUrl?: string;
  captionRiskFlags?: string[];
  samePageImageCount?: number;
  samePageCaptionCount?: number;
  storedFilename?: string;
  storedRelativePath?: string;
  storedAbsolutePath?: string;
  imageNum?: number;
  objectId?: string;
  pageCount?: number;
  folderLabel?: string;
  page?: number;
  pageRange?: number[];
  confidence?: "high" | "medium" | "low";
  evidence?: string;
  primaryAnchor?: VerseId;
  coverageRanges?: Array<{ start: VerseId; end?: VerseId }>;
  relatedRanges?: Array<{ start: VerseId; end?: VerseId }>;
  sourceId?: string;
  sourceStream?: string;
  sourceLabel?: string;
  documentRole?: string;
  commentaryKey?: string;
  runId?: string;
  schemaVersion?: number;
  generatedAt?: string;
  bodyChars?: number;
  subtype?: string;
  heading?: string;
  estimatedSpan?: number;
  displayRange?: string;
  markerType?: string;
  rawMarker?: string;
  repairNote?: string;
  navigationRepair?: string;
  placementBasis?: string;
  placementScope?: string;
  navigationRisk?: string;
  riskLevel?: string;
  riskFlags?: string[];
  reviewStatus?: string;
  contentStatus?: string;
  navigationStatus?: string;
  readerInclusion?: string;
  syncStatus?: string;
  syncSelection?: string;
  sourceWorkbenchCardId?: string;
  sourceRawKind?: string;
  sourceAssetPath?: string;
  sourceKey?: string;
  bookFolder?: string;
  downloadedBytes?: number;
  navigationHrefs?: string[];
  navigationLabels?: string[];
  navigationPrimaryAnchors?: VerseId[];
}

export interface StudyResource {
  id: string;
  title: string;
  type: ResourceType;
  verses: VerseId[];
  primaryAnchor?: VerseId;
  bookIntro?: string;
  body: string;
  summary?: string;
  searchText?: string;
  source?: string;
  assetPath?: string;
  createdAt?: string;
  updatedAt?: string;
  path?: string;
  debugMeta?: StudyResourceDebugMeta;
}
