import doreChapterArtworkUrl from "./generated/doreChapterArtwork.json?url";

// Generated by scripts/generateDoreChapterArtwork.mjs from the local Doré
// illustration set (多雷圣经插图_高清版_241幅_2026-07-17). One plate per chapter,
// lowest plate number wins. Do not hand-edit the JSON; rerun the script.

export interface DoreChapterArtwork {
  page: number;
  book: string;
  chapter: number;
  title: string;
  scriptureReference: string | null;
  assetPath: string;
}

export interface DoreChapterArtworkPayload {
  generatedAt: string;
  source: string;
  maxPixelSize: number;
  entries: DoreChapterArtwork[];
}

let cachedPayload: Promise<DoreChapterArtworkPayload> | null = null;

export function loadDoreChapterArtworkPayload(): Promise<DoreChapterArtworkPayload> {
  cachedPayload ??= (import.meta.env.MODE === "test"
    ? import("./generated/doreChapterArtwork.json").then((module) => module.default as DoreChapterArtworkPayload)
    : fetch(doreChapterArtworkUrl).then(async (response) => {
      if (!response.ok) {
        throw new Error(`Failed to load Doré chapter artwork JSON: ${response.status}`);
      }
      return await response.json() as DoreChapterArtworkPayload;
    })
  ).catch((error: unknown) => {
    cachedPayload = null;
    throw error;
  });
  return cachedPayload;
}

/** Key is `${book}.${chapter}`, e.g. `Gen.1`. */
export async function loadDoreChapterArtworkByChapter(): Promise<Map<string, DoreChapterArtwork>> {
  const payload = await loadDoreChapterArtworkPayload();
  return new Map(payload.entries.map((entry) => [`${entry.book}.${entry.chapter}`, entry]));
}
