import type { StudyResource } from "../domain/resources";
import genesisCommentaryResourcesUrl from "./generated/genesisCommentaryResources.json?url";

// Generated by scripts/syncGenesisCommentaryResources.mjs from /Users/simon/OHB/Resources/01_创世记/无图经文注释卡片台账_20260514_181756/资源审计台账.jsonl.
// Source ledger generated at 2026-05-14T18:17:56+08:00. Do not hand-edit this file; update the Resources ledger and rerun the script.
interface GenesisCommentaryResourcesPayload {
  metadata: {
    sourceGeneratedAt: string;
    sourceLedgerPath: string;
    totalResources: number;
  };
  resources: StudyResource[];
}

let cachedPayload: Promise<GenesisCommentaryResourcesPayload> | null = null;

export function loadGenesisCommentaryResourcePayload(): Promise<GenesisCommentaryResourcesPayload> {
  cachedPayload ??= import.meta.env.MODE === "test"
    ? import("./generated/genesisCommentaryResources.json").then((module) => module.default as GenesisCommentaryResourcesPayload)
    : fetch(genesisCommentaryResourcesUrl).then(async (response) => {
      if (!response.ok) {
        throw new Error(`Failed to load Genesis commentary resources JSON: ${response.status}`);
      }
      return await response.json() as GenesisCommentaryResourcesPayload;
    }).catch((error: unknown) => {
      cachedPayload = null;
      throw error;
    });
  return cachedPayload;
}

export async function loadGenesisCommentaryResources(): Promise<StudyResource[]> {
  const payload = await loadGenesisCommentaryResourcePayload();
  return payload.resources;
}
